numbers =[5,2,1,7,7,4]
numbers.append(20)
print(numbers)
numbers.insert(1,11)
print(numbers)
print(numbers.index(5))
numbers.remove(5)
print(numbers)
numbers.pop()
print(numbers)
print(5 in numbers)
print(7 in numbers)
print(numbers.count(7))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2=numbers.copy()
print(numbers2)
numbers.clear()
print(numbers)